# File Paths
data_path: "data/goal"
model_name: "facebook/opt-125m"
output_dir: "models/goal" 

# Training Args
max_seq_len: 128
per_device_train_batch_size: 8
learning_rate: 1.0e-3
num_train_epochs: 50
max_steps: 130000

# Evaluation Args
eval_steps: 250 
save_steps: 500
eval_accumulation_steps: 1
per_device_eval_batch_size: 2
num_eval_examples: 2000 # Evaluation would take ~2 hours each time w/o limiting this

# Logging Args
logging_steps: 10
save_total_limit: 2

# Train from checkpoint
#checkpoint_name: "/home/ubuntu/coq-modeling/models/codellama-7b-tpe-1k/checkpoint-15700"
