# File Paths
data_path: "data/rerank-tfidf-proj-thm-final-clean"
model_name: "facebook/opt-125m"
output_dir: "models/rerank-tfidf-prof-thm-final" 

# Training Args
max_seq_len: 512
per_device_train_batch_size: 4
learning_rate: 1.0e-4
num_train_epochs: 5
max_steps: 10000
gradient_accumulation_steps: 2

# Evaluation Args
eval_steps: 500 
eval_accumulation_steps: 1
per_device_eval_batch_size: 4
save_steps: 500
num_eval_examples: 2000 # Evaluation would take ~2 hours each time w/o limiting this

# Logging Args
logging_steps: 10
save_total_limit: 2

# Train from checkpoint
#checkpoint_name: "/home/kthompson/coq-modeling/models/rerank-15-pos-opt/checkpoint-500" 

