# File Paths

data_path: "/home/kthompson/coq-modeling/data/rerank-premise-pos-rnd-split-rnd-samp-pct-8"
model_name: "google/byt5-small"
output_dir: "/home/kthompson/coq-modeling/models/rerank-15-pos-all" 

# Training Args
max_seq_len: 128 
per_device_train_batch_size: 16
learning_rate: 1.0e-5
num_train_epochs: 1
gradient_accumulation_steps: 8

# Evaluation Args
eval_steps: 500
eval_accumulation_steps: 1
per_device_eval_batch_size: 16
save_steps: 500
num_eval_examples: 2000 # Evaluation would take ~2 hours each time w/o limiting this

# Logging Args
logging_steps: 10
save_total_limit: 2

# Train from checkpoint
#checkpoint_name: "/home/kthompson/coq-modeling/models/codellama-7b-basic-rnd-split-rnd-samp/checkpoint-7459" 

